### ISSUE TITLE
Charts: y-axis automatic width calculation

### ISSUE THREAD

**Issue by nlopin** [factorialco/factorial-one#498]
## What 

Y-axis has a [fixed width](https://github.com/factorialco/factorial-one/commit/79053987be81012d4aac0a4ea41c2f18a9391021) of 32px, which fits 3-4 characters.

If the label is bigger, it is truncated. For smaller labels you can see a gap. 

![CleanShot 2024-09-13 at 08 34 50@2x](https://github.com/user-attachments/assets/92f76712-4c57-4334-a50a-29f7bea96f09)

It would be nice to automatically calculate the width of the Y-axis component.

## Context

We use `recharts` library to render charts. This library converts components into an SVG with axises, areas, etc. The library uses fixed axis width that needs manual adjustments. 

The library has a [similar issue](https://github.com/recharts/recharts/issues/2027) to resolve. Not sure if we should tackle it directly in the library or just have an in-place calculation of the width that fits our case only.

**Comment by Rogermax** [comment]
Ohh I see.. seems difficult and will take long that this fix is available for us. I will go ahead with our one solution for now
