### ISSUE TITLE
Tabbar does not animate the first transition

### ISSUE THREAD

**Issue by nlopin** [factorialco/factorial-one#654]
## Steps

1. open the tabbar example in the storybook
2. refresh the page
3. click to another tab

Expected behavior: the change of the tab is animated
Observed: it switches instantly

All the following transitions are animated

## Demo

https://github.com/user-attachments/assets/9b74ad4f-75d7-4e8e-a3c2-ad14e9d5f477

**Comment by josepjaume** [comment]
Oh wow, it only behaves like this on production!
